name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cargo build
      run: cargo build --verbose
    - name: start postgres
      run: sudo systemctl start postgresql.service
    - name: cargo test
      run: cargo test --verbose
    - name: run
      run: cargo run
